# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import virginityapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('virginityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to=virginityapp.models.dish_image_path)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_image_dish', to='virginityapp.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('description', models.CharField(max_length=256)),
                ('by', models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, related_name='gift_card_client_by', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, related_name='gift_card_client_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Tagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_dish', to='virginityapp.Dish')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_tag', to='virginityapp.Tag')),
            ],
        ),
    ]
