# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import virginityapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('virginityapp', '0002_dishimage_giftcard_tag_tagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishimage',
            name='path',
            field=models.ImageField(storage=virginityapp.models.ImgurStorage(), upload_to=''),
        ),
    ]
