# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virginityapp', '0005_orderitem_multiplicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='virginityapp.Address'),
        ),
    ]
