# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virginityapp', '0006_auto_20171223_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_order', to='virginityapp.Order'),
        ),
    ]
